# Generated by Django 4.2 on 2025-01-22 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('cafe_space_position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone_number', models.CharField(help_text='فقط 10 رقم آخر شماره تلفن را وارد کنید.', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='رمز عبور باید حداقل ۸ کاراکتر و ترکیبی از حروف، اعداد و کاراکترهای خاص باشد.', max_length=100, validators=[django.core.validators.MinLengthValidator(9, message='رمز عبور باید حداقل ۸ کاراکتر باشد.'), django.core.validators.RegexValidator(message='رمز عبور باید حداقل شامل یک حرف کوچک، یک حرف بزرگ، یک عدد و یک کاراکتر خاص باشد.', regex='^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s]){8,16}$')])),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
